project:
  type: website
  output-dir: _site


website:
  title: "Sundarajan Swaminathan"
  site-url: about.qmd
  navbar:
    pinned: true
    right:
      - text: "About"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Tools"
        href: tools.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd
  page-navigation: true
  sidebar: false
  page-footer:
    left: "Â© 2025 Sundarajan Swaminathan"
    right: "ğŸ“ Built with [Quarto](https://quarto.org) | Hosted on GitHub Pages"

format:
  html:
    theme: darkly
    css: styles.css
